<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="CqrsFoundation.Tests" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CqrsFoundation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
</Project>
